spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/parking"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
